// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wblcrbcyqfauljhhwtyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndibGNyYmN5cWZhdWxqaGh3dHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MTkxNjEsImV4cCI6MjA1MTQ5NTE2MX0.5Dxif-SH18sdDydFcbO6-yG6wt6R9V-NQaUkSnUNS9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);